# Generated by Django 4.2.1 on 2023-06-12 11:57

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico', models.TextField(blank=True, default='')),
                ('fecha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos_fecha', to='paciente.fecha')),
                ('hora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos_hora', to='paciente.hora')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos_paciente', to='paciente.paciente')),
            ],
        ),
        migrations.AlterField(
            model_name='turno',
            name='diagnostico',
            field=models.TextField(blank=True, default='', help_text='Ingrese el diagnóstico del paciente', null=True),
        ),
    ]
