# Generated by Django 4.2.1 on 2023-06-04 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fecha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Hora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.CharField(choices=[('16:30', '04:30 PM'), ('16:40', '04:40 PM'), ('16:50', '04:50 PM'), ('17:00', '05:00 PM'), ('17:10', '05:10 PM'), ('17:20', '05:20 PM'), ('17:30', '05:30 PM'), ('17:40', '05:40 PM'), ('17:50', '05:50 PM'), ('18:00', '06:00 PM'), ('18:10', '06:10 PM'), ('18:20', '06:20 PM'), ('18:30', '06:30 PM'), ('18:40', '06:40 PM'), ('18:50', '06:50 PM'), ('19:00', '07:00 PM')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('apellido', models.CharField(max_length=90)),
                ('obra_social', models.CharField(blank=True, max_length=25)),
                ('celular', models.CharField(max_length=12)),
                ('dni', models.IntegerField()),
                ('observaciones', models.TextField(blank=True)),
                ('fecha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.fecha')),
                ('hora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.hora')),
            ],
        ),
    ]
