# Generated by Django 4.2.1 on 2023-06-07 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obra_sociales', '0004_alter_obrasocial_estado'),
        ('paciente', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='hora',
        ),
        migrations.AlterField(
            model_name='paciente',
            name='obra_social',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='obra_sociales.obrasocial'),
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos_fecha', to='paciente.fecha')),
                ('hora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos_hora', to='paciente.hora')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos_paciente', to='paciente.fecha')),
            ],
        ),
    ]
