# Generated by Django 4.2.1 on 2023-06-04 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0003_auto_20230604_1912'),
    ]

    operations = [
    ]
