# Generated by Django 4.2.1 on 2023-06-07 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0004_paciente_nombre_completo_alter_hora_hora_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='diagnostico',
            field=models.TextField(blank=True, default=''),
        ),
    ]
