# Generated by Django 4.2.1 on 2023-06-10 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0005_turno_diagnostico'),
    ]

    operations = [
    ]
