# Generated by Django 4.2.1 on 2023-06-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0005_alter_fecha_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hora',
            name='hora',
            field=models.CharField(choices=[('16:00', '04:00 PM'), ('16:10', '04:10 PM'), ('16:20', '04:20 PM'), ('16:30', '04:30 PM'), ('16:40', '04:40 PM'), ('16:50', '04:50 PM'), ('17:00', '05:00 PM'), ('17:10', '05:10 PM'), ('17:20', '05:20 PM'), ('17:30', '05:30 PM'), ('17:40', '05:40 PM'), ('17:50', '05:50 PM'), ('18:00', '06:00 PM'), ('18:10', '06:10 PM'), ('18:20', '06:20 PM'), ('18:30', '06:30 PM'), ('18:40', '06:40 PM'), ('18:50', '06:50 PM'), ('19:00', '07:00 PM')], max_length=10),
        ),
    ]
