# Generated by Django 4.2.1 on 2023-06-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obra_sociales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obrasocial',
            name='estado',
            field=models.CharField(choices=[('ACT', 'Activo'), ('SUS', 'Suspendido')], max_length=100),
        ),
    ]
