# Generated by Django 4.2.1 on 2023-06-06 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obra_sociales', '0003_alter_obrasocial_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obrasocial',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Active'), ('Suspendido', 'Suspended')], max_length=100),
        ),
    ]
